version: '3.8'

services:
  database:
    build:
      context: ./DataBase
      dockerfile: Dockerfile
    environment:
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    

  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "8080:8080"  
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@database:1521:xe
      SPRING_DATASOURCE_USERNAME: DOSI  
      SPRING_DATASOURCE_PASSWORD: DOSI 
    depends_on:
      - database
    

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "3000:80"  
    

volumes:
  oracle-data:


